version: 2.0
jobs:
  test:
    docker:
      - image: circleci/python:3.6.1


    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      # run tests!
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            python tests.py

      - store_artifacts:
          path: test-reports
          destination: test-reports
  package:
    docker:
      - image: alpine:3.7


    steps:
      - checkout
      - add_ssh_keys:
         fingerprints:
          - "d9:84:c9:f4:be:20:d9:be:c5:78:d3:c4:6c:db:4e:f7"
      - run: apk add openssh
      - run:
          name: Deploy Over SSH
          command: |
            ssh ubuntu@34.77.143.146 "~/code/ca-project/compose.sh"

workflows:
  version: 2
  job_flow:
    jobs:
    - test
    - package:
        requires:
        - test
